### PR TITLE
Feature/A1SDLT-128 Update pagination logic with new API response

### PR DESCRIPTION
**Pull request by JaneMcBrain**
https://jira.catena-x.net/browse/A1SLDT-128

### CODE REVIEW

**Review by LuLeRoemer — COMMENTED** [review]
LGTM

Does it make sense to also display the total number of items? I think the API response also contains that info.

**Comment by JaneMcBrain** [comment]
> 

Yes I added that already :) You will now see something like "1 from 2 pages"

**Comment by JaneMcBrain** [comment]
> > > 
> > 
> > 
> > Yes I added that already :) You will now see something like "1 from 2 pages"
> 
> Yes, I saw that. I actually meant the total number of model items.

Ah sorry! Yes we would add that too. Just a question of where?

**Comment by LuLeRoemer** [comment]
Hm, I would suggest at the top of the page. Just as a hint to the user. But we could also do it as part of another PR, as you like, was just an additional idea. Do you know whats going on with the vulnerability scan that is failing?

**Comment by JaneMcBrain** [comment]
> Hm, I would suggest at the top of the page. Just as a hint to the user. But we could also do it as part of another PR, as you like, was just an additional idea. Do you know whats going on with the vulnerability scan that is failing?

Ok then let's keep t for now and I will prepare a new ticket for that :)

**Review by LuLeRoemer — APPROVED** [review]

**Review by drcgjung — APPROVED** [review]
LGTM

**Pull request merged**
