### PR TITLE
Implement registry API

### PR DESCRIPTION
**Pull request by fmisir**
This is the initial implementation of the Registry API.

Currently the persistent is based on a in memory collection.
The persistent will be implemented after the initial API is approved.

### CODE REVIEW

**Review by drcgjung — CHANGES_REQUESTED** [review]
1. Your branch is incorrectly named - see https://confluence.catena-x.net/display/CXM/Development+Tools
2. Your target branch is wrong. You first need to integrate with feature/CAX-1-semantics before I will forward this pull request to main
3. There will be (at the moment) no further toplevel directory "registry" as this will be a "semantics" service. Please first add your service as an additional endpoint to the existing semantics ap. Later we will refactor the semantics module.
4. Packages should be net.catenax.semantics.registry in order to make clear that its the digitial twin registry and not any other general registry.

**Comment by JaneMcBrain** [comment]
I also checked out this branch yesterday in order to start with the frontend and I was wondering about the following two points:
1. In the semantics API the url to get models is 'localhost:4243/api/v1/models' and here it is 'http://localhost:4243/twins' to get the twins. I would prefere to have the same url structure.
2. I noticed that the structure of the returned example value for /twins/{twin_id} is different to the structure of what Schorsch implemented. Is this structure still open for discussions and if so, do you plan a session for this?

**Comment by fmisir** [comment]
@JaneMcBrain 

   1. Valid point. I will change the paths of the endpoints to /api/v1/twins
   2. I'am not aware of any other implementation. Do you have a link / document where I can check?

**Comment by JaneMcBrain** [comment]
Two more questions:
1. In a twin we have aspects and in there httpEndpoints, which contains a method attribute. What does the POST type stands for?
2. In the modelReference we have only one attribute, so why having the URN attribute instead of modelReference or will there be more modelReferences attributes in the future?

**Comment by fmisir** [comment]
Regarding your questions: 

1. The method indicates on how the URL of the httpEndpoint have to be called by the consuming client (POST, PUT, GET, DELETE).
It's ok when we only consider GET for now.

2. There will be only one modelReference for an aspect. The reason for the object is that we can decide later to split the urn artifacts without breaking changes like:
"modelReference": {
        "urn": "com.baam.parts.effective.bom:1.0.2:EffectiveBOM",
        "name": "EffectiveBOM",
        "version": "1.0.2"
 }
I decided for now to not add them to the API to reduce the efforts.

**Comment by fmisir** [comment]
Closing this PR in favour for https://github.com/catenax/tractusx/pull/92.

**Pull request closed without merging**
